name: Trapper Data Modification

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: trapper_env
        python-version: 3.9

    - name: Install dependencies
      shell: bash
      run: |
        conda env update --file environment.yaml --name trapper_env
        conda env list
        conda init bash
        . ~/.bashrc
        conda activate trapper_env
        
    - name: Run script
      shell: bash
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{secrets.PASSWORD}}
      run: |
        # you may have to activate the environment before running the 
        # python script, and you likley need to say python3 vs just python
        conda init bash
        . ~/.bashrc
        conda activate graydons_env
        python3 list_agol_hub_content.py
